log-level = "debug"
listen-clients = ":8484"
send-ops = "confs/sendopsv79.properties"
recv-ops = "confs/recvopsv79.properties"
[data-source]
ip = "10.100.156.210"
port = 3306
username = "root"
password = "password#dbr"
database = "mptest"